import type {
  ActivityItem,
  AnalyticsDataPoint,
  CustomerMessage,
  EscalationRule,
  FAQ,
  MarketplaceConnection,
  Product,
  ReturnPolicy,
} from "./types";

export const STORE_PROFILE = {
  name: "Artisan Home Co.",
  owner: "Sarah Chen",
  email: "sarah@artisanhome.co",
  plan: "Growth",
  repliesUsed: 847,
  repliesLimit: 2000,
  tone: "Warm, professional, concise",
};

export const MARKETPLACE_CONNECTIONS: MarketplaceConnection[] = [
  {
    id: "conn-1",
    marketplace: "amazon",
    storeName: "Artisan Home Co. (US)",
    region: "United States",
    connectedAt: "2025-11-14T09:30:00Z",
    status: "connected",
    lastSync: "2026-07-10T19:45:00Z",
    productCount: 142,
    messageCount: 38,
  },
  {
    id: "conn-2",
    marketplace: "etsy",
    storeName: "ArtisanHomeCeramics",
    region: "Global",
    connectedAt: "2025-12-02T14:15:00Z",
    status: "connected",
    lastSync: "2026-07-10T19:42:00Z",
    productCount: 67,
    messageCount: 24,
  },
  {
    id: "conn-3",
    marketplace: "shopify",
    storeName: "artisanhome.myshopify.com",
    region: "North America & EU",
    connectedAt: "2026-01-18T11:00:00Z",
    status: "connected",
    lastSync: "2026-07-10T19:40:00Z",
    productCount: 89,
    messageCount: 19,
  },
  {
    id: "conn-4",
    marketplace: "ebay",
    storeName: "artisan_home_outlet",
    region: "United States",
    connectedAt: "2026-02-22T16:45:00Z",
    status: "syncing",
    lastSync: "2026-07-10T19:38:00Z",
    productCount: 53,
    messageCount: 12,
  },
];

export const PRODUCTS: Product[] = [
  {
    id: "prod-1",
    sku: "AHC-CER-001",
    name: "Hand-Thrown Ceramic Mug Set (4pc)",
    marketplace: "amazon",
    price: 48.99,
    currency: "USD",
    stock: 234,
    category: "Kitchen & Dining",
  },
  {
    id: "prod-2",
    sku: "AHC-TEX-012",
    name: "Organic Linen Table Runner — Sage",
    marketplace: "etsy",
    price: 34.5,
    currency: "USD",
    stock: 18,
    category: "Home Textiles",
  },
  {
    id: "prod-3",
    sku: "AHC-CAN-003",
    name: "Soy Wax Candle Trio — Lavender Fields",
    marketplace: "shopify",
    price: 29.99,
    currency: "USD",
    stock: 156,
    category: "Candles & Fragrance",
  },
  {
    id: "prod-4",
    sku: "AHC-WAL-007",
    name: "Walnut Cutting Board — Large",
    marketplace: "amazon",
    price: 62.0,
    currency: "USD",
    stock: 42,
    category: "Kitchen & Dining",
  },
  {
    id: "prod-5",
    sku: "AHC-THR-015",
    name: "Woven Cotton Throw Blanket — Cream",
    marketplace: "ebay",
    price: 54.99,
    currency: "USD",
    stock: 31,
    category: "Home Textiles",
  },
  {
    id: "prod-6",
    sku: "AHC-VAS-022",
    name: "Stoneware Vase — Matte White",
    marketplace: "etsy",
    price: 41.0,
    currency: "USD",
    stock: 9,
    category: "Decor",
  },
];

export const FAQS: FAQ[] = [
  {
    id: "faq-1",
    question: "What is your standard shipping time?",
    answer:
      "Orders ship within 1–2 business days. Domestic delivery takes 3–5 business days; international 7–14 business days depending on destination.",
    category: "Shipping",
    usageCount: 142,
  },
  {
    id: "faq-2",
    question: "Do you accept returns on custom/personalized items?",
    answer:
      "Personalized items cannot be returned unless defective. Standard items may be returned within 30 days in original condition.",
    category: "Returns",
    usageCount: 89,
  },
  {
    id: "faq-3",
    question: "Are your ceramics dishwasher-safe?",
    answer:
      "Yes, all stoneware pieces are dishwasher- and microwave-safe. Hand-painted items should be hand-washed to preserve finish.",
    category: "Product Care",
    usageCount: 67,
  },
  {
    id: "faq-4",
    question: "Do you offer wholesale pricing?",
    answer:
      "Yes, wholesale orders of 50+ units receive 20% off. Contact wholesale@artisanhome.co with your business details.",
    category: "Business",
    usageCount: 23,
  },
  {
    id: "faq-5",
    question: "How do I track my international order?",
    answer:
      "International orders include tracking via DHL eCommerce. Tracking links are emailed within 24 hours of shipment.",
    category: "Shipping",
    usageCount: 56,
  },
];

export const RETURN_POLICIES: ReturnPolicy[] = [
  {
    id: "pol-1",
    marketplace: "amazon",
    windowDays: 30,
    conditions: "Unused, original packaging. Buyer pays return shipping unless item is defective.",
    restockingFee: 0,
    lastUpdated: "2026-03-15",
  },
  {
    id: "pol-2",
    marketplace: "etsy",
    windowDays: 14,
    conditions: "Buyer responsible for return shipping. Custom orders non-refundable.",
    restockingFee: 0,
    lastUpdated: "2026-02-01",
  },
  {
    id: "pol-3",
    marketplace: "shopify",
    windowDays: 30,
    conditions: "Free return shipping on orders over $75. Restocking fee of 15% on opened items.",
    restockingFee: 15,
    lastUpdated: "2026-04-10",
  },
  {
    id: "pol-4",
    marketplace: "ebay",
    windowDays: 30,
    conditions: "30-day money-back guarantee. Seller pays return shipping for SNAD claims.",
    restockingFee: 0,
    lastUpdated: "2026-01-20",
  },
];

export const CUSTOMER_MESSAGES: CustomerMessage[] = [
  {
    id: "msg-1",
    customerName: "Marie Dubois",
    customerEmail: "marie.dubois@email.fr",
    marketplace: "amazon",
    orderId: "AMZ-114-7829341",
    subject: "Où est ma commande?",
    originalMessage:
      "Bonjour, j'ai commandé le set de mugs il y a 5 jours et je n'ai toujours pas reçu de numéro de suivi. Pouvez-vous m'aider?",
    detectedLanguage: "French",
    languageFlag: "🇫🇷",
    category: "shipping",
    sentiment: "neutral",
    status: "draft_ready",
    receivedAt: "2026-07-10T14:22:00Z",
    productName: "Hand-Thrown Ceramic Mug Set (4pc)",
    productSku: "AHC-CER-001",
    orderAmount: 48.99,
    currency: "USD",
    aiDraft:
      "Bonjour Marie,\n\nMerci pour votre message et pour votre commande chez Artisan Home Co. Votre colis (commande AMZ-114-7829341) a été expédié hier via USPS Priority Mail. Votre numéro de suivi est 9400 1000 0000 0284 7283 12 — vous pouvez le suivre sur usps.com.\n\nLa livraison internationale vers la France prend généralement 7 à 14 jours ouvrables. N'hésitez pas à nous recontacter si vous avez d'autres questions.\n\nCordialement,\nSarah — Artisan Home Co.",
    confidence: 0.94,
    tone: "Warm, professional",
  },
  {
    id: "msg-2",
    customerName: "James Whitfield",
    customerEmail: "j.whitfield@gmail.com",
    marketplace: "etsy",
    orderId: "ETY-8829104",
    subject: "Damaged item received",
    originalMessage:
      "Hi, one of the mugs in my set arrived cracked. Very disappointed — this was a gift. I need a replacement or full refund ASAP.",
    detectedLanguage: "English",
    languageFlag: "🇺🇸",
    category: "returns",
    sentiment: "negative",
    status: "escalated",
    receivedAt: "2026-07-10T11:05:00Z",
    productName: "Hand-Thrown Ceramic Mug Set (4pc)",
    productSku: "AHC-CER-001",
    orderAmount: 48.99,
    currency: "USD",
    aiDraft:
      "Hi James,\n\nI'm truly sorry to hear one of the mugs arrived damaged — that's absolutely not the experience we want for you, especially for a gift. I've flagged this for priority handling.\n\nPer our Etsy return policy, we'll send a prepaid return label and ship a replacement set at no charge, or issue a full refund — whichever you prefer. Could you share a photo of the damage so we can file a claim with our shipping carrier?\n\nWe'll make this right.\n\nWarm regards,\nSarah — Artisan Home Co.",
    confidence: 0.78,
    tone: "Empathetic, solution-focused",
    escalationReason: "Negative sentiment + refund request",
  },
  {
    id: "msg-3",
    customerName: "Yuki Tanaka",
    customerEmail: "yuki.t@yahoo.co.jp",
    marketplace: "shopify",
    orderId: "SHP-44921",
    subject: "キャンドルの燃焼時間について",
    originalMessage:
      "こんにちは。ラベンダーキャンドル3個セットを購入しました。1個あたりの燃焼時間はどのくらいですか？また、香りはどのくらい持続しますか？",
    detectedLanguage: "Japanese",
    languageFlag: "🇯🇵",
    category: "product",
    sentiment: "neutral",
    status: "draft_ready",
    receivedAt: "2026-07-10T09:18:00Z",
    productName: "Soy Wax Candle Trio — Lavender Fields",
    productSku: "AHC-CAN-003",
    orderAmount: 29.99,
    currency: "USD",
    aiDraft:
      "田中様\n\nご購入ありがとうございます。ラベンダーフィールドズ ソイワックスキャンドルについてお答えします。\n\n1個あたりの燃焼時間は約45〜50時間です。100%天然ソイワックスを使用しており、パラフィンよりも長く燃焼します。香りは点灯中は部屋全体に広がり、消灯後も2〜3時間ほど残ります。\n\nご不明な点がございましたら、お気軽にお問い合わせください。\n\nArtisan Home Co. より",
    confidence: 0.96,
    tone: "Polite, informative",
  },
  {
    id: "msg-4",
    customerName: "Elena Rodríguez",
    customerEmail: "elena.r@outlook.es",
    marketplace: "ebay",
    orderId: "EBY-7738291",
    subject: "¿Puedo cambiar la dirección de envío?",
    originalMessage:
      "Hola, acabo de darme cuenta de que puse la dirección antigua. ¿Es posible cambiarla antes de que se envíe? La dirección correcta es Calle Mayor 15, 28013 Madrid.",
    detectedLanguage: "Spanish",
    languageFlag: "🇪🇸",
    category: "order",
    sentiment: "neutral",
    status: "draft_ready",
    receivedAt: "2026-07-10T08:45:00Z",
    productName: "Woven Cotton Throw Blanket — Cream",
    productSku: "AHC-THR-015",
    orderAmount: 54.99,
    currency: "USD",
    aiDraft:
      "Hola Elena,\n\n¡Por supuesto! Acabo de verificar tu pedido EBY-7738291 y aún no ha sido enviado, así que podemos actualizar la dirección sin problema.\n\nHe cambiado la dirección de envío a:\nCalle Mayor 15, 28013 Madrid, España\n\nRecibirás un correo de confirmación de eBay en breve. Tu pedido se enviará mañana.\n\n¡Gracias por avisarnos!\n\nSaludos,\nSarah — Artisan Home Co.",
    confidence: 0.91,
    tone: "Friendly, helpful",
  },
  {
    id: "msg-5",
    customerName: "Thomas Müller",
    customerEmail: "t.mueller@web.de",
    marketplace: "amazon",
    orderId: "AMZ-114-7829102",
    subject: "Rückgabe Schneidebrett",
    originalMessage:
      "Guten Tag, das Schneidebrett ist kleiner als erwartet. Ich möchte es zurückgeben. Wie läuft das ab?",
    detectedLanguage: "German",
    languageFlag: "🇩🇪",
    category: "returns",
    sentiment: "neutral",
    status: "draft_ready",
    receivedAt: "2026-07-09T16:30:00Z",
    productName: "Walnut Cutting Board — Large",
    productSku: "AHC-WAL-007",
    orderAmount: 62.0,
    currency: "USD",
    aiDraft:
      "Guten Tag Thomas,\n\nvielen Dank für Ihre Nachricht. Es tut uns leid, dass das Schneidebrett nicht Ihren Erwartungen entspricht.\n\nGemäß unserer Amazon-Rückgaberichtlinie haben Sie 30 Tage ab Erhalt Zeit für eine Rücksendung. Ich habe Ihnen ein vorfrankiertes Rücksendeetikett per E-Mail zugesandt. Nach Eingang der Ware erstatten wir den vollen Betrag von 62,00 USD.\n\nDie Abmessungen des Bretts (18\" × 12\" × 1,5\") finden Sie auf der Produktseite — falls wir die Beschreibung verbessern können, lassen Sie es uns wissen.\n\nMit freundlichen Grüßen,\nSarah — Artisan Home Co.",
    confidence: 0.93,
    tone: "Formal, clear",
  },
  {
    id: "msg-6",
    customerName: "Sophie Laurent",
    customerEmail: "sophie.l@free.fr",
    marketplace: "etsy",
    orderId: "ETY-8828956",
    subject: "Question sur l'entretien du vase",
    originalMessage:
      "Bonjour ! Le vase en grès est-il compatible lave-vaisselle ? Et peut-on y mettre de l'eau fraîche pour des fleurs coupées ?",
    detectedLanguage: "French",
    languageFlag: "🇫🇷",
    category: "product",
    sentiment: "positive",
    status: "auto_sent",
    receivedAt: "2026-07-09T10:15:00Z",
    productName: "Stoneware Vase — Matte White",
    productSku: "AHC-VAS-022",
    orderAmount: 41.0,
    currency: "USD",
    aiDraft:
      "Bonjour Sophie !\n\nOui, notre vase en grès est entièrement compatible lave-vaisselle et vous pouvez bien sûr y mettre de l'eau fraîche pour vos bouquets. Le grès est étanche et ne nécessite aucun traitement particulier.\n\nPour préserver l'éclat du fini mat, nous recommandons un lavage doux à la main de temps en temps.\n\nMerci pour votre confiance !\n\nSarah — Artisan Home Co.",
    confidence: 0.97,
    tone: "Warm, concise",
    responseTime: "4 min",
  },
  {
    id: "msg-7",
    customerName: "David Park",
    customerEmail: "dpark@naver.com",
    marketplace: "shopify",
    orderId: "SHP-44890",
    subject: "배송 지연 문의",
    originalMessage:
      "안녕하세요, 3일 전에 주문했는데 아직 배송이 시작되지 않았습니다. 언제쯤 받을 수 있을까요?",
    detectedLanguage: "Korean",
    languageFlag: "🇰🇷",
    category: "shipping",
    sentiment: "neutral",
    status: "sent",
    receivedAt: "2026-07-08T22:40:00Z",
    productName: "Organic Linen Table Runner — Sage",
    productSku: "AHC-TEX-012",
    orderAmount: 34.5,
    currency: "USD",
    aiDraft:
      "박David님, 안녕하세요.\n\n주문해 주셔서 감사합니다. SHP-44890 주문 건은 현재 출고 준비 중이며, 내일(7월 9일) 발송 예정입니다. 국제 배송은 보통 7~10일 소요됩니다.\n\n배송 시작 시 추적 번호를 이메일로 보내드리겠습니다. 추가 문의 사항이 있으시면 언제든 연락 주세요.\n\n감사합니다,\nSarah — Artisan Home Co.",
    confidence: 0.95,
    tone: "Polite, reassuring",
    responseTime: "12 min",
  },
  {
    id: "msg-8",
    customerName: "Anna Kowalski",
    customerEmail: "anna.k@gmail.com",
    marketplace: "amazon",
    orderId: "AMZ-114-7828901",
    subject: "Refund not received",
    originalMessage:
      "I returned the candle set 2 weeks ago and still haven't received my refund. This is unacceptable. I want my $29.99 back NOW or I'm filing a chargeback.",
    detectedLanguage: "English",
    languageFlag: "🇺🇸",
    category: "returns",
    sentiment: "negative",
    status: "escalated",
    receivedAt: "2026-07-08T15:20:00Z",
    productName: "Soy Wax Candle Trio — Lavender Fields",
    productSku: "AHC-CAN-003",
    orderAmount: 29.99,
    currency: "USD",
    aiDraft:
      "Hi Anna,\n\nI completely understand your frustration, and I apologize for the delay. I've looked into your return (AMZ-114-7828901) and can confirm we received the package on July 3rd.\n\nIt appears the refund was processed on our end but may not have reflected on your payment method yet — Amazon refunds can take 3–5 business days to appear. I've escalated this to our finance team for immediate resolution and will personally follow up within 24 hours.\n\nYou should see $29.99 credited by end of day tomorrow at the latest.\n\nSincerely,\nSarah — Artisan Home Co.",
    confidence: 0.72,
    tone: "Apologetic, urgent",
    escalationReason: "Refund dispute + chargeback threat",
  },
];

export const ESCALATION_RULES: EscalationRule[] = [
  {
    id: "rule-1",
    name: "Negative Sentiment",
    description: "Flag messages with negative sentiment score below -0.3 for human review",
    enabled: true,
    triggerCount: 23,
    lastTriggered: "2026-07-10T11:05:00Z",
  },
  {
    id: "rule-2",
    name: "Refund Requests",
    description: "Escalate any message mentioning refund, chargeback, or money-back",
    enabled: true,
    triggerCount: 17,
    lastTriggered: "2026-07-08T15:20:00Z",
  },
  {
    id: "rule-3",
    name: "Low AI Confidence",
    description: "Queue for review when draft confidence score is below 0.85",
    enabled: true,
    triggerCount: 31,
    lastTriggered: "2026-07-09T14:30:00Z",
  },
  {
    id: "rule-4",
    name: "High-Value Orders",
    description: "Escalate messages for orders over $200 for personal attention",
    enabled: false,
    triggerCount: 4,
    lastTriggered: "2026-06-28T09:00:00Z",
  },
  {
    id: "rule-5",
    name: "Repeat Complaints",
    description: "Flag customers with 2+ negative messages in 30 days",
    enabled: true,
    triggerCount: 8,
    lastTriggered: "2026-07-07T18:45:00Z",
  },
];

export const ACTIVITY_FEED: ActivityItem[] = [
  {
    id: "act-1",
    type: "auto_sent",
    description: "Auto-replied to Sophie Laurent (French product care question) — confidence 0.97",
    timestamp: "2026-07-09T10:19:00Z",
    marketplace: "etsy",
  },
  {
    id: "act-2",
    type: "escalated",
    description: "Escalated James Whitfield — damaged item + refund request",
    timestamp: "2026-07-10T11:08:00Z",
    marketplace: "etsy",
  },
  {
    id: "act-3",
    type: "reply_sent",
    description: "Approved and sent reply to David Park (Korean shipping inquiry)",
    timestamp: "2026-07-08T22:52:00Z",
    marketplace: "shopify",
  },
  {
    id: "act-4",
    type: "sync",
    description: "Synced 142 products and 3 policy updates from Amazon",
    timestamp: "2026-07-10T19:45:00Z",
    marketplace: "amazon",
  },
  {
    id: "act-5",
    type: "escalated",
    description: "Escalated Anna Kowalski — refund dispute with chargeback threat",
    timestamp: "2026-07-08T15:25:00Z",
    marketplace: "amazon",
  },
  {
    id: "act-6",
    type: "reply_sent",
    description: "Edited and sent German return instructions to Thomas Müller",
    timestamp: "2026-07-09T17:15:00Z",
    marketplace: "amazon",
  },
  {
    id: "act-7",
    type: "connected",
    description: "eBay store connected — syncing 53 listings",
    timestamp: "2026-02-22T16:45:00Z",
    marketplace: "ebay",
  },
  {
    id: "act-8",
    type: "auto_sent",
    description: "Auto-replied to routine shipping FAQ — Marco Bianchi (Italian)",
    timestamp: "2026-07-07T14:30:00Z",
    marketplace: "amazon",
  },
];

export const ANALYTICS_DATA: AnalyticsDataPoint[] = [
  { day: "Mon", replies: 42, autoReplies: 28, escalations: 3, avgResponseMinutes: 8.2 },
  { day: "Tue", replies: 38, autoReplies: 25, escalations: 2, avgResponseMinutes: 7.5 },
  { day: "Wed", replies: 51, autoReplies: 35, escalations: 4, avgResponseMinutes: 9.1 },
  { day: "Thu", replies: 45, autoReplies: 31, escalations: 3, avgResponseMinutes: 6.8 },
  { day: "Fri", replies: 56, autoReplies: 40, escalations: 5, avgResponseMinutes: 7.2 },
  { day: "Sat", replies: 33, autoReplies: 24, escalations: 1, avgResponseMinutes: 5.9 },
  { day: "Sun", replies: 29, autoReplies: 21, escalations: 2, avgResponseMinutes: 6.4 },
];

export const WEEKLY_STATS = {
  totalReplies: 294,
  autoReplyRate: 68.4,
  avgResponseMinutes: 7.3,
  escalationRate: 6.8,
  languagesServed: 8,
  topMarketplace: "Amazon",
  timeSavedHours: 18.5,
};

export const MARKETPLACE_LABELS: Record<string, string> = {
  amazon: "Amazon",
  ebay: "eBay",
  etsy: "Etsy",
  shopify: "Shopify",
};

export const MARKETPLACE_COLORS: Record<string, string> = {
  amazon: "bg-orange-500/20 text-orange-300 border-orange-500/30",
  ebay: "bg-red-500/20 text-red-300 border-red-500/30",
  etsy: "bg-amber-500/20 text-amber-300 border-amber-500/30",
  shopify: "bg-green-500/20 text-green-300 border-green-500/30",
};

export const AVAILABLE_MARKETPLACES = [
  { id: "amazon", name: "Amazon", description: "Seller Central & SP-API" },
  { id: "ebay", name: "eBay", description: "Trading API & OAuth" },
  { id: "etsy", name: "Etsy", description: "Open API v3" },
  { id: "shopify", name: "Shopify", description: "Admin API & webhooks" },
];
