import Link from "next/link";
import {
  ArrowRight,
  Bot,
  Check,
  ExternalLink,
  Lightbulb,
  Search,
  TrendingUp,
} from "lucide-react";
import { Header } from "@/components/Header";

const validationItems = [
  { label: "10+ posts with this pain", passed: true },
  { label: "Paying for inferior solution", passed: true },
  { label: "Reachable channel", passed: true },
  { label: "MVP < 4 weeks", passed: true },
  { label: "Price point high enough", passed: true },
  { label: "Hair-on-fire problem", passed: true },
  { label: "Can pre-sell", passed: true },
  { label: "< 3 competitors", passed: true },
  { label: "AI-agent operable", passed: true },
];

const painPoints = [
  {
    problem:
      "Drafting customer replies across multiple languages and marketplaces is complex, requiring gathering product info, FAQs, policies, and maintaining store tone before sending.",
    persona: "Ecommerce seller managing multiple marketplaces",
    workaround:
      "Manually gathering product details, FAQs, and policies, then drafting and copying replies",
    frequency: "daily",
    wtp: "Built custom macOS app (GlobalCustomer AI) to solve this problem",
    url: "https://www.reddit.com/r/SideProject/comments/1u7guup/i_built_a_localfirst_mac_app_that_helps_ecommerce/",
  },
];

export default function ResearchPage() {
  return (
    <>
      <Header active="research" />
      <div className="mx-auto max-w-4xl px-4 py-12 sm:px-6 lg:px-8">
        <div className="mb-12 text-center">
          <div className="mb-4 inline-flex items-center gap-2 rounded-full border border-brand-500/30 bg-brand-600/10 px-4 py-1.5 text-sm text-brand-300">
            <Search className="h-4 w-4" />
            Idea Miner research
          </div>
          <h1 className="font-display text-4xl font-bold text-white">
            How we found this idea
          </h1>
          <p className="mt-4 text-lg text-slate-400">
            MarketplaceReplyBot scored <strong className="text-white">122/130</strong>{" "}
            on the weighted rubric and passed{" "}
            <strong className="text-white">9/9</strong> validation checks.
          </p>
        </div>

        {/* Why research program exists */}
        <section className="mb-10 glass-panel p-8">
          <h2 className="mb-4 flex items-center gap-2 font-display text-2xl font-bold text-white">
            <Lightbulb className="h-6 w-6 text-brand-400" />
            Why this research program exists
          </h2>
          <p className="mb-4 text-slate-300">
            This app was auto-generated by the <strong>Idea Miner</strong> pipeline
            — a twice-daily research program that hunts for validated micro-SaaS
            opportunities from real people expressing real pain online (Reddit,
            Hacker News, Stack Exchange, GitHub, and more).
          </p>
          <h3 className="mb-3 font-semibold text-white">What we&apos;re looking for</h3>
          <ul className="space-y-2 text-sm text-slate-400">
            <li className="flex items-start gap-2">
              <Check className="mt-0.5 h-4 w-4 shrink-0 text-brand-400" />
              <span>
                <strong className="text-slate-300">Self-running micro-SaaS</strong>{" "}
                — one specific problem, a small dedicated user base, minimal manual
                ops (digital-nomad friendly).
              </span>
            </li>
            <li className="flex items-start gap-2">
              <Check className="mt-0.5 h-4 w-4 shrink-0 text-brand-400" />
              <span>
                <strong className="text-slate-300">AI-agent operable</strong> —
                daily support, content, and processing handled by autonomous agents
                on self-hosted LLMs (not locked into expensive cloud API token
                bills).
              </span>
            </li>
            <li className="flex items-start gap-2">
              <Check className="mt-0.5 h-4 w-4 shrink-0 text-brand-400" />
              <span>
                <strong className="text-slate-300">Real pain only</strong> — every
                idea must trace back to actual posts where people complain, ask
                &ldquo;is there a tool for X?&rdquo;, or say &ldquo;I wish someone
                would build…&rdquo;.
              </span>
            </li>
            <li className="flex items-start gap-2">
              <Check className="mt-0.5 h-4 w-4 shrink-0 text-brand-400" />
              <span>
                <strong className="text-slate-300">
                  B2B &amp; recurring revenue preferred
                </strong>{" "}
                — higher willingness to pay, lower churn.
              </span>
            </li>
            <li className="flex items-start gap-2">
              <Check className="mt-0.5 h-4 w-4 shrink-0 text-brand-400" />
              <span>
                <strong className="text-slate-300">
                  Markets with &lt;3 established competitors
                </strong>{" "}
                — room for a focused wedge.
              </span>
            </li>
            <li className="flex items-start gap-2">
              <Check className="mt-0.5 h-4 w-4 shrink-0 text-brand-400" />
              <span>
                <strong className="text-slate-300">MVP in under 4 weeks</strong> —
                solo-dev buildable, no regulatory/hardware/capital barriers.
              </span>
            </li>
          </ul>
        </section>

        {/* Why demo was built */}
        <section className="mb-10 glass-panel p-8">
          <h2 className="mb-4 font-display text-2xl font-bold text-white">
            Why this demo was built
          </h2>
          <p className="text-slate-300">
            When an idea passes the validation gate (≥8/9 checklist items, not
            declining on Google Trends, not previously built), the pipeline
            automatically ships a working mock on Vercel so we can see the product
            story, not just a slide deck.
          </p>
        </section>

        {/* This specific idea */}
        <section className="mb-10 glass-panel p-8">
          <h2 className="mb-4 flex items-center gap-2 font-display text-2xl font-bold text-white">
            <Bot className="h-6 w-6 text-brand-400" />
            This specific idea
          </h2>
          <div className="mb-6 grid gap-4 sm:grid-cols-2">
            <div className="rounded-lg border border-slate-700 bg-surface-700/30 p-4">
              <p className="text-sm text-slate-500">Cluster</p>
              <p className="font-medium text-white">
                Multilingual Ecommerce Customer Support
              </p>
            </div>
            <div className="rounded-lg border border-slate-700 bg-surface-700/30 p-4">
              <p className="text-sm text-slate-500">Score</p>
              <p className="font-display text-2xl font-bold text-brand-300">
                122/130
              </p>
            </div>
          </div>
          <p className="mb-6 text-slate-300">
            <strong className="text-white">Why we built this demo:</strong> Policy
            and catalog context is injected at draft time — replies are accurate to
            the seller&apos;s actual rules, not generic AI fluff; self-hosted LLM
            keeps costs near zero at scale.
          </p>

          <h3 className="mb-3 font-semibold text-white">Product specification</h3>
          <p className="mb-4 text-sm text-slate-400">
            <strong className="text-slate-300">Target customer:</strong> Ecommerce
            sellers managing 2+ marketplaces (Amazon, eBay, Etsy, Shopify) with
            international customers
          </p>

          <h4 className="mb-2 text-sm font-semibold text-slate-300">
            Core MVP features
          </h4>
          <ul className="mb-6 space-y-2 text-sm text-slate-400">
            <li className="flex items-start gap-2">
              <Check className="mt-0.5 h-4 w-4 shrink-0 text-brand-400" />
              Connect marketplace accounts via API; auto-ingest product catalog,
              FAQs, and return policies
            </li>
            <li className="flex items-start gap-2">
              <Check className="mt-0.5 h-4 w-4 shrink-0 text-brand-400" />
              AI drafts context-aware replies in customer&apos;s detected language,
              matching store tone
            </li>
            <li className="flex items-start gap-2">
              <Check className="mt-0.5 h-4 w-4 shrink-0 text-brand-400" />
              One-click approve or edit before sending; optional fully-auto mode for
              routine queries
            </li>
            <li className="flex items-start gap-2">
              <Check className="mt-0.5 h-4 w-4 shrink-0 text-brand-400" />
              Escalation rules: flag negative sentiment or refund requests for
              human review
            </li>
            <li className="flex items-start gap-2">
              <Check className="mt-0.5 h-4 w-4 shrink-0 text-brand-400" />
              Weekly analytics dashboard showing reply volume, average response time,
              and escalation rate
            </li>
          </ul>

          <div className="grid gap-4 sm:grid-cols-2">
            <div className="rounded-lg border border-slate-700 bg-surface-700/30 p-4">
              <p className="text-sm text-slate-500">Pricing</p>
              <p className="text-sm text-slate-300">
                $49/mo (500 replies), $99/mo (2,000 replies), $249/mo (unlimited)
              </p>
            </div>
            <div className="rounded-lg border border-slate-700 bg-surface-700/30 p-4">
              <p className="text-sm text-slate-500">Go-to-market</p>
              <p className="text-sm text-slate-300">
                Reddit r/ecommerce, r/FulfillmentByAmazon, Etsy seller forums, cold
                outreach to sellers with negative reviews citing slow responses
              </p>
            </div>
          </div>

          <div className="mt-4 rounded-lg border border-slate-700 bg-surface-700/30 p-4">
            <p className="text-sm text-slate-500">Competitive landscape</p>
            <p className="mt-1 text-sm text-slate-300">
              Gorgias and Freshdesk exist but are generic helpdesks; no niche tool
              focused on multilingual marketplace-specific reply drafting with policy
              context injection
            </p>
          </div>

          <div className="mt-4 rounded-lg border border-slate-700 bg-surface-700/30 p-4">
            <p className="text-sm text-slate-500">Agentic automation plan</p>
            <p className="mt-1 text-sm text-slate-300">
              AI agent polls new messages every 5 minutes, retrieves relevant
              product/policy context via RAG, drafts reply, scores confidence —
              auto-sends if confidence &gt;0.92, else queues for human review; daily
              digest email generated automatically
            </p>
          </div>

          <div className="mt-4 rounded-lg border border-slate-700 bg-surface-700/30 p-4">
            <p className="text-sm text-slate-500">MVP estimate</p>
            <p className="mt-1 text-sm text-slate-300">
              Python FastAPI backend + Next.js frontend + self-hosted Mistral/LLaMA
              for drafting + marketplace OAuth integrations; 3 weeks to launch with
              Amazon SP-API and Etsy API first
            </p>
          </div>
        </section>

        {/* Validation checklist */}
        <section className="mb-10 glass-panel p-8">
          <h2 className="mb-4 flex items-center gap-2 font-display text-2xl font-bold text-white">
            <TrendingUp className="h-6 w-6 text-brand-400" />
            Validation checklist (9/9)
          </h2>
          <div className="grid gap-2 sm:grid-cols-2">
            {validationItems.map((item) => (
              <div
                key={item.label}
                className="flex items-center gap-2 rounded-lg border border-green-500/20 bg-green-500/5 px-4 py-2.5"
              >
                <Check className="h-4 w-4 text-green-400" />
                <span className="text-sm text-slate-300">{item.label}</span>
              </div>
            ))}
          </div>
        </section>

        {/* Source pain points */}
        <section className="mb-10 glass-panel p-8">
          <h2 className="mb-6 font-display text-2xl font-bold text-white">
            Source pain points (real posts)
          </h2>
          {painPoints.map((point) => (
            <div
              key={point.url}
              className="rounded-lg border border-slate-700 bg-surface-700/30 p-6"
            >
              <h3 className="font-medium text-white">{point.problem}</h3>
              <dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2">
                <div>
                  <dt className="text-slate-500">Persona</dt>
                  <dd className="text-slate-300">{point.persona}</dd>
                </div>
                <div>
                  <dt className="text-slate-500">Workaround</dt>
                  <dd className="text-slate-300">{point.workaround}</dd>
                </div>
                <div>
                  <dt className="text-slate-500">Frequency</dt>
                  <dd className="text-slate-300">{point.frequency}</dd>
                </div>
                <div>
                  <dt className="text-slate-500">WTP signal</dt>
                  <dd className="text-slate-300">{point.wtp}</dd>
                </div>
              </dl>
              <a
                href={point.url}
                target="_blank"
                rel="noopener noreferrer"
                className="mt-4 inline-flex items-center gap-1.5 text-sm text-brand-400 hover:underline"
              >
                View source post
                <ExternalLink className="h-3.5 w-3.5" />
              </a>
            </div>
          ))}
          <p className="mt-6 text-xs text-slate-500">
            Generated by Idea Miner run 2026-07-10-pm on 2026-07-10 20:27 UTC
          </p>
        </section>

        <div className="text-center">
          <Link href="/demo" className="btn-primary px-8 py-3">
            Try the interactive demo
            <ArrowRight className="h-4 w-4" />
          </Link>
        </div>
      </div>
    </>
  );
}
